version: '3.8'

services:
  cf1-ai-analyzer:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - CF1_BACKEND_URL=${CF1_BACKEND_URL:-http://host.docker.internal:3001}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET:-cf1-ai-webhook-secret-key}
    volumes:
      - ./temp:/app/temp
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s