[build]
target = "wasm32-unknown-unknown"

[env]
RUSTFLAGS = "-C link-arg=-s"

[target.wasm32-unknown-unknown]
rustflags = [
  "-C", "link-arg=-s",           # Strip symbols for smaller binary
  "-C", "opt-level=z",           # Optimize for size
  "-C", "lto=fat",              # Full link-time optimization
  "-C", "codegen-units=1",      # Single codegen unit for better optimization
]